config/routes.rb
Rails.application.routes.draw do
  resources :terminals
  resources :enderecos
  resources :linhas
  resources :tipos
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "linhas#index"
end

app/models/linha.rb
class Linha < ApplicationRecord
  belongs_to :tipo
  has_and_belongs_to_many :terminals, -> { distinct }
  validates :nome, :codigo, :tipo, :presence => true
  validates :codigo, length: {is:3}
end

app/controllers/linhas_controller.rb
class LinhasController < ApplicationController
  before_action :set_linha, only: %i[ show edit update destroy ]

  # GET /linhas or /linhas.json
  def index
    @linhas = Linha.all
  end

  # GET /linhas/1 or /linhas/1.json
  def show
  end

  # GET /linhas/new
  def new
    @linha = Linha.new
  end

  # GET /linhas/1/edit
  def edit
  end

  # POST /linhas or /linhas.json
  def create
    @linha = Linha.new(linha_params)
    params[:linha][:terminals].each do |t| 
      @terminal = Terminal.find_by(id: t)
      if @terminal
        @linha.terminals << @terminal
      end
    end
    respond_to do |format|
      if @linha.save
        format.html { redirect_to linha_url(@linha), notice: "Linha was successfully created." }
        format.json { render :show, status: :created, location: @linha }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @linha.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /linhas/1 or /linhas/1.json
  def update
    @linha.terminals.destroy_all
    params[:linha][:terminals].each do |t| 
      @terminal = Terminal.find_by(id: t)
      if @terminal
        @linha.terminals << @terminal
      end
    end
    respond_to do |format|
      if @linha.update(linha_params)
        format.html { redirect_to linha_url(@linha), notice: "Linha was successfully updated." }
        format.json { render :show, status: :ok, location: @linha }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @linha.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /linhas/1 or /linhas/1.json
  def destroy
    @linha.destroy

    respond_to do |format|
      format.html { redirect_to linhas_url, notice: "Linha was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_linha
      @linha = Linha.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def linha_params
      params.require(:linha).permit(:nome, :codigo, :tipo_id)
    end
end

app/helpers/linhas_helper.rb
module LinhasHelper
end

app/views/linhas/_form.html.erb
<%= form_with(model: linha, html: {class: "my_form"}) do |form| %>
  <% if linha.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(linha.errors.count, "error") %> prohibited this linha from being saved:</h2>

      <ul>
        <% linha.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :nome, style: "display: block" %>
    <%= form.text_field :nome %>
  </div>

  <div>
    <%= form.label :codigo, style: "display: block" %>
    <%= form.number_field :codigo %>
  </div>

  <div>
    <%= form.label :tipo_id, style: "display: block" %>
    <div class="form_radio_items">
      <%= form.collection_radio_buttons :tipo_id, Tipo.order(:name), :id, :nome %>
    </div>
  </div>

  <div style="margin-top:30px">
    <%= form.label :terminals, style: "display: block" %>
    <div class="form_radio_items">
      <%= form.collection_check_boxes :terminals, Terminal.order(:name), :id, :nome %>
    </div>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/linhas/_linha.html.erb
<div id="<%= dom_id linha %>">

  <div class="linha_block" style="color: <%= get_color_by_tipo(linha.tipo) %>">

    <span> 
      <%= linha.codigo %> 
    </span>
    
    <%= link_to linha.nome, linha %>
    
    <%= link_to linha.tipo.nome, linha.tipo %>

  </div>

</div>

app/views/linhas/edit.html.erb
<h1>Editing linha</h1>

<%= render "form", linha: @linha %>

<br>

<div>
  <%= link_to "Show this linha", @linha %> |
  <%= link_to "Back to linhas", linhas_path %>
</div>

app/views/linhas/index.html.erb
<div style="margin: auto;position: relative;max-width: 600px;">

  <p style="color: green"><%= notice %></p>

  <h1>Linhas de Ônibus</h1>

  <%= link_to "New linha", new_linha_path, class:"new_link" %>

  <div id="linhas">
    <% @linhas.each do |linha| %>
      <%= render linha %>
    <% end %>
  </div>
</div>

app/views/linhas/new.html.erb
<h1>New linha</h1>

<%= render "form", linha: @linha %>

<br>

<div>
  <%= link_to "Back to linhas", linhas_path %>
</div>

app/views/linhas/show.html.erb
<div style="margin: auto;position: relative;max-width: 400px;">

  <p style="color: green"><%= notice %></p>
  <h2>
    <%= render @linha %>
  </h2>

  <div>
    <h4>Terminais:</h4>
    <% @linha.terminals.each do |terminal| %>
      <%= render terminal %>
    <% end %>
  </div>

  <div class="show_functions">
    <%= link_to "Edit this linha", edit_linha_path(@linha) %> |
    <%= link_to "Back to linhas", linhas_path %>

    <%= button_to "Destroy this linha", @linha, method: :delete %>
  </div>

  </div>