config/routes.rb
Rails.application.routes.draw do
  resources :terminals
  resources :enderecos
  resources :linhas
  resources :tipos
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "linhas#index"
end

app/models/endereco.rb
class Endereco < ApplicationRecord
    has_one :terminal
    validates :rua, :numero, :presence => true
end

app/controllers/enderecos_controller.rb
class EnderecosController < ApplicationController
  before_action :set_endereco, only: %i[ show edit update destroy ]

  # GET /enderecos or /enderecos.json
  def index
    @enderecos = Endereco.all
  end

  # GET /enderecos/1 or /enderecos/1.json
  def show
  end

  # GET /enderecos/new
  def new
    @endereco = Endereco.new
  end

  # GET /enderecos/1/edit
  def edit
  end

  # POST /enderecos or /enderecos.json
  def create
    @endereco = Endereco.new(endereco_params)

    respond_to do |format|
      if @endereco.save
        format.html { redirect_to endereco_url(@endereco), notice: "Endereco was successfully created." }
        format.json { render :show, status: :created, location: @endereco }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @endereco.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /enderecos/1 or /enderecos/1.json
  def update
    respond_to do |format|
      if @endereco.update(endereco_params)
        format.html { redirect_to endereco_url(@endereco), notice: "Endereco was successfully updated." }
        format.json { render :show, status: :ok, location: @endereco }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @endereco.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /enderecos/1 or /enderecos/1.json
  def destroy
    @endereco.destroy

    respond_to do |format|
      format.html { redirect_to enderecos_url, notice: "Endereco was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_endereco
      @endereco = Endereco.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def endereco_params
      params.require(:endereco).permit(:rua, :numero)
    end
end

app/helpers/enderecos_helper.rb
module EnderecosHelper
end

app/views/enderecos/_endereco.html.erb
<div id="<%= dom_id endereco %>">
  <p>
    <%= endereco.id %> - 
    <%= endereco.rua %>, 
    <%= endereco.numero %>
  </p>

</div>

app/views/enderecos/_form.html.erb
<%= form_with(model: endereco, html: {class: "my_form"}) do |form| %>
  <% if endereco.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(endereco.errors.count, "error") %> prohibited this endereco from being saved:</h2>

      <ul>
        <% endereco.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :rua, style: "display: block" %>
    <%= form.text_field :rua %>
  </div>

  <div>
    <%= form.label :numero, style: "display: block" %>
    <%= form.number_field :numero %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/enderecos/edit.html.erb
<h1>Editing endereco</h1>

<%= render "form", endereco: @endereco %>

<br>

<div>
  <%= link_to "Show this endereco", @endereco %> |
  <%= link_to "Back to enderecos", enderecos_path %>
</div>

app/views/enderecos/index.html.erb
<div style="margin: auto;position: relative;max-width: 350px;">

  <p style="color: green"><%= notice %></p>

  <h1>Enderecos</h1>

  <div id="enderecos">
    <% @enderecos.each do |endereco| %>
      <%= render endereco %>
    <% end %>
  </div>

  <%= link_to "New endereco", new_endereco_path, class:"new_link" %>
</div>

app/views/enderecos/new.html.erb
<h1>New endereco</h1>

<%= render "form", endereco: @endereco %>

<br>

<div>
  <%= link_to "Back to enderecos", enderecos_path %>
</div>

app/views/enderecos/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @endereco %>

<div>
  <%= link_to "Edit this endereco", edit_endereco_path(@endereco) %> |
  <%= link_to "Back to enderecos", enderecos_path %>

  <%= button_to "Destroy this endereco", @endereco, method: :delete %>
</div>