config/routes.rb
Rails.application.routes.draw do
  resources :terminals
  resources :enderecos
  resources :linhas
  resources :tipos
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "linhas#index"
end

app/models/terminal.rb
class Terminal < ApplicationRecord
  belongs_to :endereco, :dependent => :destroy
  has_and_belongs_to_many :linhas, -> { distinct }

  validates :nome, :presence => true
end

app/controllers/terminals_controller.rb
class TerminalsController < ApplicationController
  before_action :set_terminal, only: %i[ show edit update destroy ]

  # GET /terminals or /terminals.json
  def index
    @terminals = Terminal.all
  end

  # GET /terminals/1 or /terminals/1.json
  def show
  end

  # GET /terminals/new
  def new
    @terminal = Terminal.new
  end

  # GET /terminals/1/edit
  def edit
  end

  # POST /terminals or /terminals.json
  def create
    @terminal = Terminal.new(terminal_params)

    respond_to do |format|
      if @terminal.save
        format.html { redirect_to terminal_url(@terminal), notice: "Terminal was successfully created." }
        format.json { render :show, status: :created, location: @terminal }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @terminal.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /terminals/1 or /terminals/1.json
  def update
    respond_to do |format|
      if @terminal.update(terminal_params)
        format.html { redirect_to terminal_url(@terminal), notice: "Terminal was successfully updated." }
        format.json { render :show, status: :ok, location: @terminal }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @terminal.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /terminals/1 or /terminals/1.json
  def destroy
    @terminal.destroy

    respond_to do |format|
      format.html { redirect_to terminals_url, notice: "Terminal was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_terminal
      @terminal = Terminal.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def terminal_params
      params.require(:terminal).permit(:nome, :endereco_id)
    end
end

app/helpers/terminals_helper.rb
module TerminalsHelper
end

app/views/terminals/_form.html.erb
<%= form_with(model: terminal, html: {class: "my_form"}) do |form| %>
  <% if terminal.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(terminal.errors.count, "error") %> prohibited this terminal from being saved:</h2>

      <ul>
        <% terminal.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :nome, style: "display: block" %>
    <%= form.text_field :nome %>
  </div>

  <div>
    <%= form.label :endereco_id, style: "display: block" %>
    <%= form.text_field :endereco_id %>
    <em>
      <% Endereco.all.each do |endereco| %>
        <%= render endereco %>
      <% end %>
    </em>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/terminals/_terminal.html.erb
<div id="<%= dom_id terminal %>">

  <div class="terminal_block" >

    <%= link_to terminal.nome, terminal %>
    <span> 
      <%= terminal.endereco.rua %>, <%= terminal.endereco.numero %>
    </span>

    </div>
</div>

app/views/terminals/edit.html.erb
<h1>Editing terminal</h1>

<%= render "form", terminal: @terminal %>

<br>

<div>
  <%= link_to "Show this terminal", @terminal %> |
  <%= link_to "Back to terminals", terminals_path %>
</div>

app/views/terminals/index.html.erb
<div style="margin: auto;position: relative;max-width: 450px;">

  <p style="color: green"><%= notice %></p>

  <h1>Terminais</h1>
  
  <%= link_to "New terminal", new_terminal_path, class:"new_link" %>

  <div id="terminals">
    <% @terminals.each do |terminal| %>
      <%= render terminal %>
    <% end %>
  </div>

</div>

app/views/terminals/new.html.erb
<h1>New terminal</h1>

<%= render "form", terminal: @terminal %>

<br>

<div>
  <%= link_to "Back to terminals", terminals_path %>
</div>

app/views/terminals/show.html.erb
<div style="margin: auto;position: relative;max-width: 350px;">

  <p style="color: green"><%= notice %></p>
  
  <h2>
    <%= render @terminal %>
  </h2>

  <div>
    <h4>Linhas:</h4>
    <% @terminal.linhas.each do |linha| %>
      <%= render linha %>
    <% end %>
  </div>


  <div class="show_functions">
    <%= link_to "Edit this terminal", edit_terminal_path(@terminal) %> |
    <%= link_to "Back to terminals", terminals_path %>

    <%= button_to "Destroy this terminal", @terminal, method: :delete %>
  </div>
</div>